// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM admin_users
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin_users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, created_at
`

type CreateAdminParams struct {
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Username, arg.Email, arg.PasswordHash)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO admin_sessions (admin_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, admin_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	AdminID   uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

type CreateSessionRow struct {
	ID        uuid.UUID
	AdminID   uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession, arg.AdminID, arg.TokenHash, arg.ExpiresAt)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM admin_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, username, email, password_hash, created_at
FROM admin_users
WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, email, password_hash, created_at
FROM admin_users
WHERE username = $1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, admin_id, token_hash, expires_at, created_at
FROM admin_sessions
WHERE token_hash = $1
`

type GetSessionByHashRow struct {
	ID        uuid.UUID
	AdminID   uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) GetSessionByHash(ctx context.Context, tokenHash string) (GetSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, tokenHash)
	var i GetSessionByHashRow
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
