// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    tenant_id, client_id, name, description, enabled, public_client, secret,
    root_url, home_url, redirect_uris, post_logout_redirect_uris, default_scopes,
    direct_access_grants, service_accounts, implicit_flow, device_flow,
    pkce, consent_required, access_token_lifespan, id_token_signature_alg, full_scope_allowed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
) RETURNING id, tenant_id, client_id, name, description, enabled, public_client, secret, root_url, home_url, redirect_uris, post_logout_redirect_uris, default_scopes, direct_access_grants, service_accounts, implicit_flow, device_flow, pkce, consent_required, access_token_lifespan, id_token_signature_alg, full_scope_allowed, created_at
`

type CreateClientParams struct {
	TenantID               uuid.UUID
	ClientID               string
	Name                   string
	Description            string
	Enabled                bool
	PublicClient           bool
	Secret                 string
	RootUrl                string
	HomeUrl                string
	RedirectUris           []string
	PostLogoutRedirectUris []string
	DefaultScopes          []string
	DirectAccessGrants     bool
	ServiceAccounts        bool
	ImplicitFlow           bool
	DeviceFlow             bool
	Pkce                   string
	ConsentRequired        bool
	AccessTokenLifespan    int32
	IDTokenSignatureAlg    string
	FullScopeAllowed       bool
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.TenantID,
		arg.ClientID,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.PublicClient,
		arg.Secret,
		arg.RootUrl,
		arg.HomeUrl,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.DefaultScopes,
		arg.DirectAccessGrants,
		arg.ServiceAccounts,
		arg.ImplicitFlow,
		arg.DeviceFlow,
		arg.Pkce,
		arg.ConsentRequired,
		arg.AccessTokenLifespan,
		arg.IDTokenSignatureAlg,
		arg.FullScopeAllowed,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.PublicClient,
		&i.Secret,
		&i.RootUrl,
		&i.HomeUrl,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.DefaultScopes,
		&i.DirectAccessGrants,
		&i.ServiceAccounts,
		&i.ImplicitFlow,
		&i.DeviceFlow,
		&i.Pkce,
		&i.ConsentRequired,
		&i.AccessTokenLifespan,
		&i.IDTokenSignatureAlg,
		&i.FullScopeAllowed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, tenant_id, client_id, name, description, enabled, public_client, secret, root_url, home_url, redirect_uris, post_logout_redirect_uris, default_scopes, direct_access_grants, service_accounts, implicit_flow, device_flow, pkce, consent_required, access_token_lifespan, id_token_signature_alg, full_scope_allowed, created_at FROM clients WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.PublicClient,
		&i.Secret,
		&i.RootUrl,
		&i.HomeUrl,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.DefaultScopes,
		&i.DirectAccessGrants,
		&i.ServiceAccounts,
		&i.ImplicitFlow,
		&i.DeviceFlow,
		&i.Pkce,
		&i.ConsentRequired,
		&i.AccessTokenLifespan,
		&i.IDTokenSignatureAlg,
		&i.FullScopeAllowed,
		&i.CreatedAt,
	)
	return i, err
}

const getClientByClientID = `-- name: GetClientByClientID :one
SELECT id, tenant_id, client_id, name, description, enabled, public_client, secret, root_url, home_url, redirect_uris, post_logout_redirect_uris, default_scopes, direct_access_grants, service_accounts, implicit_flow, device_flow, pkce, consent_required, access_token_lifespan, id_token_signature_alg, full_scope_allowed, created_at FROM clients WHERE tenant_id = $1 AND client_id = $2
`

type GetClientByClientIDParams struct {
	TenantID uuid.UUID
	ClientID string
}

func (q *Queries) GetClientByClientID(ctx context.Context, arg GetClientByClientIDParams) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByClientID, arg.TenantID, arg.ClientID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.PublicClient,
		&i.Secret,
		&i.RootUrl,
		&i.HomeUrl,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.DefaultScopes,
		&i.DirectAccessGrants,
		&i.ServiceAccounts,
		&i.ImplicitFlow,
		&i.DeviceFlow,
		&i.Pkce,
		&i.ConsentRequired,
		&i.AccessTokenLifespan,
		&i.IDTokenSignatureAlg,
		&i.FullScopeAllowed,
		&i.CreatedAt,
	)
	return i, err
}

const listClientsByTenant = `-- name: ListClientsByTenant :many
SELECT id, tenant_id, client_id, name, description, enabled, public_client, secret, root_url, home_url, redirect_uris, post_logout_redirect_uris, default_scopes, direct_access_grants, service_accounts, implicit_flow, device_flow, pkce, consent_required, access_token_lifespan, id_token_signature_alg, full_scope_allowed, created_at FROM clients WHERE tenant_id = $1 ORDER BY created_at
`

func (q *Queries) ListClientsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClientsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.PublicClient,
			&i.Secret,
			&i.RootUrl,
			&i.HomeUrl,
			&i.RedirectUris,
			&i.PostLogoutRedirectUris,
			&i.DefaultScopes,
			&i.DirectAccessGrants,
			&i.ServiceAccounts,
			&i.ImplicitFlow,
			&i.DeviceFlow,
			&i.Pkce,
			&i.ConsentRequired,
			&i.AccessTokenLifespan,
			&i.IDTokenSignatureAlg,
			&i.FullScopeAllowed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients SET
    name = $2, description = $3, enabled = $4, public_client = $5, secret = $6,
    root_url = $7, home_url = $8, redirect_uris = $9, post_logout_redirect_uris = $10,
    default_scopes = $11, direct_access_grants = $12, service_accounts = $13,
    implicit_flow = $14, device_flow = $15, pkce = $16, consent_required = $17,
    access_token_lifespan = $18, id_token_signature_alg = $19, full_scope_allowed = $20
WHERE id = $1
RETURNING id, tenant_id, client_id, name, description, enabled, public_client, secret, root_url, home_url, redirect_uris, post_logout_redirect_uris, default_scopes, direct_access_grants, service_accounts, implicit_flow, device_flow, pkce, consent_required, access_token_lifespan, id_token_signature_alg, full_scope_allowed, created_at
`

type UpdateClientParams struct {
	ID                     uuid.UUID
	Name                   string
	Description            string
	Enabled                bool
	PublicClient           bool
	Secret                 string
	RootUrl                string
	HomeUrl                string
	RedirectUris           []string
	PostLogoutRedirectUris []string
	DefaultScopes          []string
	DirectAccessGrants     bool
	ServiceAccounts        bool
	ImplicitFlow           bool
	DeviceFlow             bool
	Pkce                   string
	ConsentRequired        bool
	AccessTokenLifespan    int32
	IDTokenSignatureAlg    string
	FullScopeAllowed       bool
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.PublicClient,
		arg.Secret,
		arg.RootUrl,
		arg.HomeUrl,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.DefaultScopes,
		arg.DirectAccessGrants,
		arg.ServiceAccounts,
		arg.ImplicitFlow,
		arg.DeviceFlow,
		arg.Pkce,
		arg.ConsentRequired,
		arg.AccessTokenLifespan,
		arg.IDTokenSignatureAlg,
		arg.FullScopeAllowed,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.PublicClient,
		&i.Secret,
		&i.RootUrl,
		&i.HomeUrl,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.DefaultScopes,
		&i.DirectAccessGrants,
		&i.ServiceAccounts,
		&i.ImplicitFlow,
		&i.DeviceFlow,
		&i.Pkce,
		&i.ConsentRequired,
		&i.AccessTokenLifespan,
		&i.IDTokenSignatureAlg,
		&i.FullScopeAllowed,
		&i.CreatedAt,
	)
	return i, err
}

const updateClientSecret = `-- name: UpdateClientSecret :one
UPDATE clients SET secret = $2 WHERE id = $1 RETURNING id, tenant_id, client_id, name, description, enabled, public_client, secret, root_url, home_url, redirect_uris, post_logout_redirect_uris, default_scopes, direct_access_grants, service_accounts, implicit_flow, device_flow, pkce, consent_required, access_token_lifespan, id_token_signature_alg, full_scope_allowed, created_at
`

type UpdateClientSecretParams struct {
	ID     uuid.UUID
	Secret string
}

func (q *Queries) UpdateClientSecret(ctx context.Context, arg UpdateClientSecretParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClientSecret, arg.ID, arg.Secret)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.PublicClient,
		&i.Secret,
		&i.RootUrl,
		&i.HomeUrl,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.DefaultScopes,
		&i.DirectAccessGrants,
		&i.ServiceAccounts,
		&i.ImplicitFlow,
		&i.DeviceFlow,
		&i.Pkce,
		&i.ConsentRequired,
		&i.AccessTokenLifespan,
		&i.IDTokenSignatureAlg,
		&i.FullScopeAllowed,
		&i.CreatedAt,
	)
	return i, err
}
