// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminSession struct {
	ID        uuid.UUID
	AdminID   uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
	CreatedAt time.Time
}

type AdminUser struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

type Client struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	ClientID               string
	Name                   string
	Description            string
	Enabled                bool
	PublicClient           bool
	Secret                 string
	RootUrl                string
	HomeUrl                string
	RedirectUris           []string
	PostLogoutRedirectUris []string
	DefaultScopes          []string
	DirectAccessGrants     bool
	ServiceAccounts        bool
	ImplicitFlow           bool
	DeviceFlow             bool
	Pkce                   string
	ConsentRequired        bool
	AccessTokenLifespan    int32
	IDTokenSignatureAlg    string
	FullScopeAllowed       bool
	CreatedAt              time.Time
}

type Role struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
}

type Tenant struct {
	ID          uuid.UUID
	Name        string
	DisplayName string
	Enabled     bool
	CreatedAt   time.Time
}

type User struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Username     string
	Email        string
	FirstName    string
	LastName     string
	Enabled      bool
	PasswordHash *string
	CreatedAt    time.Time
}

type UserRole struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

type UserSession struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	UserAgent  string
	IpAddress  string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	RevokedAt  pgtype.Timestamptz
}

type UserSessionClient struct {
	SessionID   uuid.UUID
	ClientID    string
	FirstSeenAt time.Time
	LastSeenAt  time.Time
}
