// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (tenant_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, description, created_at
`

type CreateRoleParams struct {
	TenantID    uuid.UUID
	Name        string
	Description string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.TenantID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const filterTenantRoleIDs = `-- name: FilterTenantRoleIDs :many
SELECT id FROM roles
WHERE tenant_id = $1 AND id = ANY($2::uuid[])
`

type FilterTenantRoleIDsParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

func (q *Queries) FilterTenantRoleIDs(ctx context.Context, arg FilterTenantRoleIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, filterTenantRoleIDs, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRole = `-- name: GetRole :one
SELECT id, tenant_id, name, description, created_at
FROM roles
WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, tenant_id, name, description, created_at
FROM roles
WHERE tenant_id = $1 AND name = $2
`

type GetRoleByNameParams struct {
	TenantID uuid.UUID
	Name     string
}

func (q *Queries) GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, arg.TenantID, arg.Name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listRolesByTenant = `-- name: ListRolesByTenant :many
SELECT id, tenant_id, name, description, created_at
FROM roles
WHERE tenant_id = $1
ORDER BY created_at
`

func (q *Queries) ListRolesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = $2, description = $3
WHERE id = $1
RETURNING id, tenant_id, name, description, created_at
`

type UpdateRoleParams struct {
	ID          uuid.UUID
	Name        string
	Description string
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
