// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (tenant_id, user_id, token_hash, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, user_id, token_hash, user_agent, ip_address, created_at, last_seen_at, expires_at, revoked_at
`

type CreateUserSessionParams struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	UserAgent string
	IpAddress string
	ExpiresAt time.Time
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserSessionByHash = `-- name: GetUserSessionByHash :one
SELECT id, tenant_id, user_id, token_hash, user_agent, ip_address, created_at, last_seen_at, expires_at, revoked_at
FROM user_sessions
WHERE token_hash = $1
`

func (q *Queries) GetUserSessionByHash(ctx context.Context, tokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByHash, tokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveSessionClientsByTenant = `-- name: ListActiveSessionClientsByTenant :many
SELECT sc.session_id, sc.client_id, COALESCE(c.name, '') AS client_name, sc.first_seen_at, sc.last_seen_at
FROM user_session_clients sc
JOIN user_sessions s ON s.id = sc.session_id
LEFT JOIN clients c ON c.client_id = sc.client_id AND c.tenant_id = s.tenant_id
WHERE s.tenant_id = $1 AND s.revoked_at IS NULL AND s.expires_at > now()
ORDER BY sc.first_seen_at
`

type ListActiveSessionClientsByTenantRow struct {
	SessionID   uuid.UUID
	ClientID    string
	ClientName  string
	FirstSeenAt time.Time
	LastSeenAt  time.Time
}

func (q *Queries) ListActiveSessionClientsByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListActiveSessionClientsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listActiveSessionClientsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSessionClientsByTenantRow
	for rows.Next() {
		var i ListActiveSessionClientsByTenantRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ClientID,
			&i.ClientName,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSessionsByTenant = `-- name: ListActiveSessionsByTenant :many
SELECT s.id, s.user_id, u.username, s.user_agent, s.ip_address, s.created_at, s.last_seen_at, s.expires_at
FROM user_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.tenant_id = $1 AND s.revoked_at IS NULL AND s.expires_at > now()
ORDER BY s.last_seen_at DESC
`

type ListActiveSessionsByTenantRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Username   string
	UserAgent  string
	IpAddress  string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

func (q *Queries) ListActiveSessionsByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListActiveSessionsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSessionsByTenantRow
	for rows.Next() {
		var i ListActiveSessionsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.UserAgent,
			&i.IpAddress,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserSession = `-- name: RevokeUserSession :execrows
UPDATE user_sessions SET revoked_at = now()
WHERE id = $1 AND tenant_id = $2 AND revoked_at IS NULL
`

type RevokeUserSessionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSession, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchUserSession = `-- name: TouchUserSession :exec
UPDATE user_sessions SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchUserSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserSession, id)
	return err
}

const upsertSessionClient = `-- name: UpsertSessionClient :exec
INSERT INTO user_session_clients (session_id, client_id)
VALUES ($1, $2)
ON CONFLICT (session_id, client_id) DO UPDATE SET last_seen_at = now()
`

type UpsertSessionClientParams struct {
	SessionID uuid.UUID
	ClientID  string
}

func (q *Queries) UpsertSessionClient(ctx context.Context, arg UpsertSessionClientParams) error {
	_, err := q.db.Exec(ctx, upsertSessionClient, arg.SessionID, arg.ClientID)
	return err
}
