// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addUserRoles = `-- name: AddUserRoles :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1, unnest($2::uuid[])
`

type AddUserRolesParams struct {
	UserID  uuid.UUID
	RoleIds []uuid.UUID
}

func (q *Queries) AddUserRoles(ctx context.Context, arg AddUserRolesParams) error {
	_, err := q.db.Exec(ctx, addUserRoles, arg.UserID, arg.RoleIds)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, username, email, first_name, last_name, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, username, email, first_name, last_name, enabled, created_at
`

type CreateUserParams struct {
	TenantID  uuid.UUID
	Username  string
	Email     string
	FirstName string
	LastName  string
	Enabled   bool
}

type CreateUserRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Username  string
	Email     string
	FirstName string
	LastName  string
	Enabled   bool
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Enabled,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, username, email, first_name, last_name, enabled, created_at
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Username  string
	Email     string
	FirstName string
	LastName  string
	Enabled   bool
	CreatedAt time.Time
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, tenant_id, username, email, first_name, last_name, enabled, created_at
FROM users
WHERE tenant_id = $1 AND username = $2
`

type GetUserByUsernameParams struct {
	TenantID uuid.UUID
	Username string
}

type GetUserByUsernameRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Username  string
	Email     string
	FirstName string
	LastName  string
	Enabled   bool
	CreatedAt time.Time
}

func (q *Queries) GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, arg.TenantID, arg.Username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserCredentials = `-- name: GetUserCredentials :one
SELECT id, enabled, password_hash FROM users WHERE tenant_id = $1 AND username = $2
`

type GetUserCredentialsParams struct {
	TenantID uuid.UUID
	Username string
}

type GetUserCredentialsRow struct {
	ID           uuid.UUID
	Enabled      bool
	PasswordHash *string
}

func (q *Queries) GetUserCredentials(ctx context.Context, arg GetUserCredentialsParams) (GetUserCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentials, arg.TenantID, arg.Username)
	var i GetUserCredentialsRow
	err := row.Scan(&i.ID, &i.Enabled, &i.PasswordHash)
	return i, err
}

const listTenantUserRoles = `-- name: ListTenantUserRoles :many
SELECT ur.user_id, ur.role_id
FROM user_roles ur
JOIN users u ON u.id = ur.user_id
WHERE u.tenant_id = $1
`

func (q *Queries) ListTenantUserRoles(ctx context.Context, tenantID uuid.UUID) ([]UserRole, error) {
	rows, err := q.db.Query(ctx, listTenantUserRoles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRole
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(&i.UserID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleIDs = `-- name: ListUserRoleIDs :many
SELECT role_id FROM user_roles WHERE user_id = $1
`

func (q *Queries) ListUserRoleIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserRoleIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenant = `-- name: ListUsersByTenant :many
SELECT id, tenant_id, username, email, first_name, last_name, enabled, created_at
FROM users
WHERE tenant_id = $1
ORDER BY created_at
`

type ListUsersByTenantRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Username  string
	Email     string
	FirstName string
	LastName  string
	Enabled   bool
	CreatedAt time.Time
}

func (q *Queries) ListUsersByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListUsersByTenantRow, error) {
	rows, err := q.db.Query(ctx, listUsersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByTenantRow
	for rows.Next() {
		var i ListUsersByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, first_name = $3, last_name = $4, enabled = $5
WHERE id = $1
RETURNING id, tenant_id, username, email, first_name, last_name, enabled, created_at
`

type UpdateUserParams struct {
	ID        uuid.UUID
	Email     string
	FirstName string
	LastName  string
	Enabled   bool
}

type UpdateUserRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Username  string
	Email     string
	FirstName string
	LastName  string
	Enabled   bool
	CreatedAt time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Enabled,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}
